import type { NextPage } from 'next'
import Head from 'next/head'
import useTranslation from 'next-translate/useTranslation'
import styles from 'styles/Home.module.css'
import { Stack } from '@mui/material'
import MuiButton from 'components/MuiButton'
import Navbar from 'components/Navbar'

const Home: NextPage = () => {
  const { t } = useTranslation()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h2>{t('common:TEST_TEXT')}</h2>

        <Stack spacing={2} direction="row">
          <MuiButton label="First Button"/>
          <MuiButton label="Second BUtton"/>
        </Stack>
      </main>
    </div>
  )
}

export default Home
